project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    fig-width: 6
    fig-asp: 0.618
    toc: true
    comments:
      hypothesis: true
  docx: 
    fig-width: 6
    fig-asp: 0.618
  elsevier-pdf: 
    fig-width: 6
    fig-asp: 0.618



